///Create new courseoccation
POST http://localhost:3001/api/course
content-type: application/json

{
    "name":"nykurs3",
    "startdate": "2022-10-14",
    "enddate":"2022-12-25"
}
###
///Get all courseoccations

GET http://localhost:3001/api/course

###
///Delete courseoccation

DELETE  http://localhost:3001/api/course/12
