//getAllUsers
GET http://localhost:3001/api/users 

###
///gerUserById
GET http://localhost:3001/api/users/1 HTTP/1.1

###
//createNewUser
POST http://localhost:3001/api/users
Content-Type:  application/json

{
    "email":"rune7@hot.com",
    "password":"Hej12345!",
    "role":"admin"
}



###
//deleteUser
DELETE http://localhost:3001/api/users/2  HTTP/1.1









